"""Model-facing specs for the MCP tool categories.

Single-definition rule: these ``{name, description, parameters}`` dicts
are THE prompt-side specs for the computer / filesystem / web tools —
:mod:`src.agent.mcp.server` exposes the same tools over MCP (arg names
match exactly), :mod:`src.tools.terminal` filters them per request, and
:mod:`src.agent.chat_model` renders the shortlist into native function
specs. ``MCP_TOOL_NAMES`` is the shared vocabulary (router, parser,
policy gate).
"""

__all__ = [
    "MCP_TOOL_DEFS",
    "MCP_TOOL_NAMES",
]

MCP_TOOL_DEFS = [
    {"name": "screenshot",
     "description": "Capture the screen to a PNG file; returns the path.",
     "parameters": {"type": "object",
                    "properties": {"path": {"type": "string"}}}},
    {"name": "click",
     "description": "Click at screen coordinates x, y.",
     "parameters": {"type": "object",
                    "properties": {"x": {"type": "integer"},
                                   "y": {"type": "integer"},
                                   "button": {"type": "string"}},
                    "required": ["x", "y"]}},
    {"name": "type_text",
     "description": "Type text into the focused window.",
     "parameters": {"type": "object",
                    "properties": {"text": {"type": "string"}},
                    "required": ["text"]}},
    {"name": "press_key",
     "description": "Press a key or +-combo like ctrl+alt+t.",
     "parameters": {"type": "object",
                    "properties": {"key": {"type": "string"}},
                    "required": ["key"]}},
    {"name": "scroll",
     "description": "Scroll vertically: clicks > 0 up, < 0 down.",
     "parameters": {"type": "object",
                    "properties": {"clicks": {"type": "integer"},
                                   "x": {"type": "integer"},
                                   "y": {"type": "integer"}},
                    "required": ["clicks"]}},
    {"name": "get_active_window",
     "description": "Return the active window id/pid/name.",
     "parameters": {"type": "object", "properties": {}}},
    {"name": "list_windows",
     "description": "List visible windows (id + name).",
     "parameters": {"type": "object",
                    "properties": {"limit": {"type": "integer"}}}},
    {"name": "open_app",
     "description": "Launch an application by executable name.",
     "parameters": {"type": "object",
                    "properties": {"name": {"type": "string"},
                                   "args": {"type": "string"}},
                    "required": ["name"]}},
    {"name": "list_directory",
     "description": "List a directory (dirs first, trailing /).",
     "parameters": {"type": "object",
                    "properties": {"path": {"type": "string"}}}},
    {"name": "search_files",
     "description": "Glob-search under root, recursive.",
     "parameters": {"type": "object",
                    "properties": {"root": {"type": "string"},
                                   "pattern": {"type": "string"}}}},
    {"name": "read_file",
     "description": "Read text lines (1-based offset, at most limit).",
     "parameters": {"type": "object",
                    "properties": {"path": {"type": "string"},
                                   "offset": {"type": "integer"},
                                   "limit": {"type": "integer"}},
                    "required": ["path"]}},
    {"name": "write_file",
     "description": "Write (create or overwrite) a text file.",
     "parameters": {"type": "object",
                    "properties": {"path": {"type": "string"},
                                   "content": {"type": "string"}},
                    "required": ["path", "content"]}},
    {"name": "edit_file",
     "description": "Exact string replacement in a text file.",
     "parameters": {"type": "object",
                    "properties": {"path": {"type": "string"},
                                   "old_string": {"type": "string"},
                                   "new_string": {"type": "string"}},
                    "required": ["path", "old_string", "new_string"]}},
    {"name": "move_file",
     "description": "Move/rename a file or directory.",
     "parameters": {"type": "object",
                    "properties": {"src": {"type": "string"},
                                   "dst": {"type": "string"}},
                    "required": ["src", "dst"]}},
    {"name": "delete_file",
     "description": "Delete a file or directory (dirs need recursive).",
     "parameters": {"type": "object",
                    "properties": {"path": {"type": "string"},
                                   "recursive": {"type": "boolean"}},
                    "required": ["path"]}},
    {"name": "search_web",
     "description": "Web search, returns titles/URLs/snippets.",
     "parameters": {"type": "object",
                    "properties": {"query": {"type": "string"}},
                    "required": ["query"]}},
    {"name": "open_url",
     "description": "Open a URL in the OS default browser.",
     "parameters": {"type": "object",
                    "properties": {"url": {"type": "string"}},
                    "required": ["url"]}},
    {"name": "extract_page",
     "description": "Extract a web page URL as text.",
     "parameters": {"type": "object",
                    "properties": {"url": {"type": "string"}},
                    "required": ["url"]}},
    {"name": "browser_click",
     "description": "Click a CSS selector on a page; report after.",
     "parameters": {"type": "object",
                    "properties": {"url": {"type": "string"},
                                   "selector": {"type": "string"}},
                    "required": ["url", "selector"]}},
    {"name": "browser_type",
     "description": "Fill text into a CSS selector (+Enter if submit).",
     "parameters": {"type": "object",
                    "properties": {"url": {"type": "string"},
                                   "selector": {"type": "string"},
                                   "text": {"type": "string"},
                                   "submit": {"type": "boolean"}},
                    "required": ["url", "selector", "text"]}},
    {"name": "browser_scroll",
     "description": "Scroll a page up/down by pixels; report after.",
     "parameters": {"type": "object",
                    "properties": {"url": {"type": "string"},
                                   "direction": {"type": "string"}}}},
    {"name": "download_file",
     "description": "Download a URL to a local path.",
     "parameters": {"type": "object",
                    "properties": {"url": {"type": "string"},
                                   "dest": {"type": "string"}},
                    "required": ["url", "dest"]}},
]

MCP_TOOL_NAMES = tuple(t["name"] for t in MCP_TOOL_DEFS)
